config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount ActionCable.server => '/cable' # Ruta para WebSocket
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }, controllers: {
    invitations: 'devise/invitations' # Agregas el controlador para manejar las invitaciones
  }

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "landing/index"
  get 'docs', to: 'landing#docs'
  get "up" => "rails/health#show", as: :rails_health_check
  get '/health', to: 'health#health'

  resources :users
  resources :categories
  resources :products
  resources :product_histories
  resources :links
  root 'landing#index'

   # Rutas para la API
   namespace :api do
    namespace :v1 do
      post 'auth/register', to: 'api_user#register'
      post 'auth/login', to: 'api_user#login'
      put 'auth/subscription', to: 'api_user#subscription'
      delete 'auth/subscription', to: 'api_user#unsubscription'
      get 'auth/mysubscriptions', to: 'api_user#mysubscriptions'
      get 'auth/list_categories', to: 'api_user#list_categories'
    end
   end
end

app/views/shared/_footer.html.erb
<!-- _footer.html.erb -->
<footer class="bg-green-900 text-white py-8">
  <div class="container mx-auto px-4">
    <%# <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      <!-- Column 1 -->
      <div>
        <h3 class="text-xl font-semibold">Cursolandia</h3>
        <p class="mt-4">We provide the best courses for you. Learn from the best instructors in the industry.</p>
      </div>

      <!-- Column 2 -->
      <div>
        <h4 class="text-lg font-semibold">Quick Links</h4>
        <ul class="mt-4 space-y-2">
          <li><a href="#home" class="hover:text-gray-400">Home</a></li>
          <li><a href="#services" class="hover:text-gray-400">Courses</a></li>
          <li><a href="#about" class="hover:text-gray-400">About</a></li>
          <li><a href="#contact" class="hover:text-gray-400">Contact</a></li>
        </ul>
      </div>

      <!-- Column 3 -->
      <div>
        <h4 class="text-lg font-semibold">Follow Us</h4>
        <div class="mt-4 flex space-x-4">
          <!-- Social icons -->
        </div>
      </div>
    </div> %>
    <div class="text-center mt-8 text-gray-400">
    &copy; 2024 Scrappy. All rights reserved. <br/>
    <blockquote class="italic">
        You can do big things with small teams, but it’s hard to do small things with big teams. - 37Signals
    </blockquote>
    </div>

  </div>
</footer>

app/views/shared/_header.html.erb
<!-- _header.html.erb -->
<header class="bg-gray-100 shadow-md"> <!-- Fondo gris aplicado al header -->
  <div class="container mx-auto px-4 py-4 flex justify-between items-center">
    <!-- Logo/Naming of the App -->
    <div class="text-4xl font-bold flex items-center text-green-500" >
      <a href="/" class="hover:text-blue-400">Price Scrappy</a>
      <%= image_tag "scrappy.png", alt: "scrappy", class: "mr-2 max-h-24" %>

    </div>

    <!-- Navigation -->
    <nav class="space-x-6 hidden md:flex">

      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <a href="<%= users_path %>" class="bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300"> <!-- Fondo gris aplicado al botón -->
            <h3>Usuarios</h3>
          </a>
          <a href="<%= categories_path %>" class="bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300"> <!-- Fondo gris aplicado al botón -->
            <h3>Categorías</h3>
          </a>
          <a href="<%= products_path %>" class="bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300"> <!-- Fondo gris aplicado al botón -->
            <h3>Productos</h3>
          </a>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300" %>
        <% else %>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300" %>
        <% end %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300" %>
      <% end %>
    </nav>

    <!-- Mobile Menu Icon -->
    <div class="md:hidden">
      <button id="menu-button" class="text-gray-800 focus:outline-none">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
        </svg>
      </button>
    </div>
  </div>

  <!-- Mobile Menu -->
  <div id="mobile-menu" class="hidden bg-gray-100 md:hidden"> <!-- Fondo gris aplicado al menú móvil -->
    <a href="<%= users_path %>" class="block bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300"> <!-- Fondo gris aplicado -->
      <h3>Usuarios</h3>
    </a>
    <a href="<%= categories_path %>" class="block bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300"> <!-- Fondo gris aplicado -->
      <h3>Categorías</h3>
    </a>
    <a href="<%= products_path %>" class="block bg-gray-100 rounded-lg shadow-lg p-4 hover:bg-gray-200 transition duration-300"> <!-- Fondo gris aplicado -->
      <h3>Productos</h3>
    </a>
    
  </div>
</header>

<script>
  // Toggle mobile menu
  document.getElementById('menu-button').addEventListener('click', function() {
    var mobileMenu = document.getElementById('mobile-menu');
    mobileMenu.classList.toggle('hidden');
  });
</script>