config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount ActionCable.server => '/cable' # Ruta para WebSocket
  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }, controllers: {
    invitations: 'devise/invitations' # Agregas el controlador para manejar las invitaciones
  }

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "landing/index"
  get 'docs', to: 'landing#docs'
  get "up" => "rails/health#show", as: :rails_health_check
  get '/health', to: 'health#health'

  resources :users
  resources :categories
  resources :products
  resources :product_histories
  resources :links
  root 'landing#index'

   # Rutas para la API
   namespace :api do
    namespace :v1 do
      post 'auth/register', to: 'api_user#register'
      post 'auth/login', to: 'api_user#login'
      put 'auth/subscription', to: 'api_user#subscription'
      delete 'auth/subscription', to: 'api_user#unsubscription'
      get 'auth/mysubscriptions', to: 'api_user#mysubscriptions'
      get 'auth/list_categories', to: 'api_user#list_categories'
    end
   end
end

app/models/product_history.rb
class ProductHistory < ApplicationRecord
  before_create :process_notifications
  belongs_to :product

  private

  def process_notifications

    # Obtiene el último precio registrado (histórico) de este producto
    last_history = ProductHistory.where(product_id: self.product_id).order(id: :desc).first

    # Verifica si el último precio era mayor que el nuevo precio
    if last_history && last_history.price > self.price
      Notification.create(
        product_id: self.product_id,
        status: :pending,
        category_id: self.product.category_id,
        message: "¡Oferta! El producto #{self.product.name} ha bajado de precio de #{last_history.price} a #{self.price}. ¡Adquiérelo ahora en #{self.product.url} !"
      )
    end

    if last_history && last_history.price < self.price
      Notification.create(
        product_id: self.product_id,
        status: :pending,
        category_id: self.product.category_id,
        message: "¡Atencion! El producto #{self.product.name} ha subido de precio de #{last_history.price} a #{self.price}. ¡Adquiérelo ahora en #{self.product.url} !"
      )
    end
  end
end

app/controllers/product_histories_controller.rb
class ProductHistoriesController < ApplicationController
  before_action :set_product_history, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end
  # GET /product_histories or /product_histories.json
  def index
    @product_histories = ProductHistory.all
  end

  # GET /product_histories/1 or /product_histories/1.json
  def show
  end

  # GET /product_histories/new
  def new
    @product_history = ProductHistory.new
  end

  # GET /product_histories/1/edit
  def edit
  end

  # POST /product_histories or /product_histories.json
  def create
    @product_history = ProductHistory.new(product_history_params)

    respond_to do |format|
      if @product_history.save
        format.html { redirect_to @product_history, notice: "Product history was successfully created." }
        format.json { render :show, status: :created, location: @product_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_histories/1 or /product_histories/1.json
  def update
    respond_to do |format|
      if @product_history.update(product_history_params)
        format.html { redirect_to @product_history, notice: "Product history was successfully updated." }
        format.json { render :show, status: :ok, location: @product_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_histories/1 or /product_histories/1.json
  def destroy
    @product_history.destroy!

    respond_to do |format|
      format.html { redirect_to product_histories_path, status: :see_other, notice: "Product history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_history
      @product_history = ProductHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_history_params
      params.require(:product_history).permit(:price, :product_id)
    end
end

app/helpers/product_histories_helper.rb
module ProductHistoriesHelper
end

app/views/product_histories/_form.html.erb
<%= form_with(model: product_history, class: "contents") do |form| %>
  <% if product_history.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product_history.errors.count, "error") %> prohibited this product_history from being saved:</h2>

      <ul>
        <% product_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/product_histories/_product_history.html.erb
<div id="<%= dom_id product_history %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product_history.price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Product:</strong>
    <%= product_history.product_id %>
  </p>

</div>

app/views/product_histories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product history</h1>

  <%= render "form", product_history: @product_history %>

  <%= link_to "Show this product history", @product_history, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to product histories", product_histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/product_histories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Product histories" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Product histories</h1>
    <%= link_to "New product history", new_product_history_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="product_histories" class="min-w-full">
    <% @product_histories.each do |product_history| %>
      <%= render product_history %>
      <p>
        <%= link_to "Show this product history", product_history, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/product_histories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product history</h1>

  <%= render "form", product_history: @product_history %>

  <%= link_to "Back to product histories", product_histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/product_histories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product_history %>

    <%= link_to "Edit this product history", edit_product_history_path(@product_history), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to product histories", product_histories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product history", @product_history, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>